language: java
jdk:
- openjdk8
- openjdk9
- openjdk10
- openjdk11
- openjdk12
- openjdk13
- openjdk14
- openjdk-ea

script:
- mvn --batch-mode install
- cd common && mvn --batch-mode -Pp2 p2:site && cd ..
- cd assertj && mvn --batch-mode -Pgen assertj:generate-assertions && cd ..
