language: java
jdk:
- openjdk8
- openjdk9
- openjdk12
- openjdk13
- openjdk14

script:
- mvn --batch-mode package
- cd common && mvn --batch-mode -Pp2 p2:site && cd ..
- cd assertj && mvn --batch-mode -Pgen assertj:generate-assertions && cd ..