before_install:
- if [ "$TRAVIS_JDK_VERSION" = "openjdk9" -a "$TRAVIS_ARCH" = "ppc64le" ]; then cd "$TRAVIS_BUILD_DIR" ;wget https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9.0.4%2B11/OpenJDK9U-jdk_ppc64le_linux_hotspot_9.0.4_11.tar.gz; tar -xvf OpenJDK9U-jdk_ppc64le_linux_hotspot_9.0.4_11.tar.gz; fi
- if [ "$TRAVIS_JDK_VERSION" = "openjdk9" -a "$TRAVIS_ARCH" = "ppc64le" ]; then export PATH=$TRAVIS_BUILD_DIR/jdk-9.0.4+11/bin:$PATH; export JAVA_HOME=$TRAVIS_BUILD_DIR/jdk-9.0.4+11; fi
- if [ "$TRAVIS_ARCH" = "ppc64le" ]; then sudo apt install maven;mvn -version; fi

language: java
dist: xenial
sudo: required
arch:
- amd64
- ppc64le
jdk:
- openjdk8
- openjdk9
- openjdk12
- openjdk13
- openjdk14

script:
- mvn --batch-mode package
- cd common && mvn --batch-mode -Pp2 p2:site && cd ..
- cd assertj && mvn --batch-mode -Pgen assertj:generate-assertions && cd ..
